### ISSUE TITLE
Link for Slack Workspace registration isn't available anymore

### ISSUE THREAD

**Issue by gregorwolf** [abap-community/abap-community#3]
Hi @damir-majer,

I've just tried to use the [ABAP Community Slack channel](https://join.slack.com/t/abapcommunity/shared_invite/enQtNTA3ODQwNTExMzE3LTVjMTZhNDBjMmYxYWFkZWY4N2ZiNTJhNTM5MjZlNDcyMzgyYWZkNGM2ZjFkMjRjYWE2NTBmYzdhZDhjZmFhZTE) link from the README.md but it does bring you to a page saying "This link is no longer active".

CU
Gregor

**Comment by damir-majer** [comment]
Hi @gregorwolf , 
the Link was corrected.. Thanks for documenting this issue!
